.PHONY: clean All

All:
	@echo "----------Building project:[ ET_Programa - Debug ]----------"
	@cd "ET_Programa" && $(MAKE) -f  "ET_Programa.mk"
clean:
	@echo "----------Cleaning project:[ ET_Programa - Debug ]----------"
	@cd "ET_Programa" && $(MAKE) -f  "ET_Programa.mk" clean
